platform :ios, '11.0'
use_frameworks! :linkage => :static

target 'breakmycircle_sim' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'SwiftHTTP', '~> 3.0.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end

target 'breakmycircle_arm' do
  pod 'Google-Mobile-Ads-SDK'
  pod 'SwiftHTTP', '~> 3.0.1'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end
